//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazynDNAProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class wydania
    {
        public int id_zamowienia { get; set; }
        public Nullable<int> id_artykulu { get; set; }
        public Nullable<int> id_pracownika { get; set; }
        public Nullable<int> ilosc_sztuk { get; set; }
        public Nullable<System.DateTime> data_wydania { get; set; }
    
        public virtual artykuly artykuly { get; set; }
        public virtual pracownicy pracownicy { get; set; }
    }
}
